Bartnik wierzejska
VD-section-1/Phase2Image pull request #7
Opened 2024-02-18 17:46 UTC by NikodemBartnik

2024-02-18 18:02 UTC, swietjak approved these changes
Cool, very nice

2024-02-18 18:47 UTC, SzymonSiakala requested changes

2024-02-18 18:47 UTC, SzymonSiakala commented on data/dataset.zip
You deleted the dataset, I can't merge it.

2024-02-18 21:11 UTC, NikodemBartnik commented
pls approve

2024-02-19 18:55 UTC, SzymonSiakala approved these changes
Very cool, very nice

2024-02-19 18:55 UTC, merged